### ISSUE TITLE
Wayland support and no audio 

### ISSUE THREAD

**Issue by VarLad** [flathub/in.cinny.Cinny#2]
Since the Pulseaudio socket isn't enabled, videos don't have audio
Wayland works seamlessly, except for videos which require gstreamer-vaapi plugin flatpak to be installed manually
Note that this plugin also breaks video playing on GNOME Web flatpak
The Wayland experience is much smoother than its XWayland counterpart on Wayland (Playing videos take ~0.5-1% more CPU on Wayland though)

**Comment by kfiven** [comment]
I have enabled the pulseaudio but for wayland see upstream issue https://github.com/tauri-apps/tauri/issues/4635

**Comment by ralf1307** [comment]
Hi! Wayland with Cinny inside an flatpak should probably work now with [this mr](https://github.com/tauri-apps/tao/pull/543). Tao has not yet proper wayland support, but now the GDK_BACKEND=wayland is going to work without crashing immediately on startup.
