### ISSUE TITLE
No emojis in flatpak

### ISSUE THREAD

**Issue by hunger** [flathub/in.cinny.Cinny#37]
Hi there!

I do not see any emoji in Cinny from flathub.org. They are all displayed as a box.

I do have emojis in non-flatpak applications and even in other flatpaks (like discord), so that seems to be an issue specific to Cinny.

Best Regards,
Tobias

PS: So far this is the best matrix client I have found:-) Thanks for working on it!

**Comment by EchedeyLR** [comment]
I confirm the same. I installed it today again after 2 months without using it.

**Comment by kfiven** [comment]
This is because of twemoji maxcdn going offline. https://github.com/cinnyapp/cinny/pull/1070 is aimed to fix it. So closing as dup.
